#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit

source ./markup
source ./popup

source ./popup_battery
# source ./popup_keyboard
source ./popup_network
source ./popup_updates
source ./popup_volume
source ./popup_vpn

# kill existing processes
pgrep -f "$(which "$0")" | grep -vE "$$" | xargs -t kill >/dev/null 2>&1

# start processes
watch_battery &
watch_volume &
watch_updates &
watch_network &
watch_vpn &

# kill the script if it's already running
kill "$(pgrep -f 'python3 ./i3ws')" >/dev/null 2>&1
python3 ./i3ws &

wait # will never happen
