#!/usr/bin/python

import i3ipc # i3ipc
from uuid import uuid4
from subprocess import Popen

uuid = str(uuid4())

def notify(self, event):
	Popen(('eventc notification workspace %s -d title="%s"' % (uuid, event.current.name)).split())

i3 = i3ipc.Connection()
i3.on('workspace::focus', notify)
i3.main()
