#!/bin/bash

popup(){
	# $1 = text
	# $2 = uuid (optional)
	# $3 = urgency (0-2, optional)
	if [[ -n "$4" ]]; then
		eventc notification generic $2 -d title="'${1//\'/\\\"}'" -d urgency="byte $3"
	else
		eventc notification generic $2 -d title="'${1//\'/\\\"}'"
	fi
}
