#!/bin/bash

VOLUME_ICON_SPEAKER=
VOLUME_ICON_HEADPHONE=

VOLUME_UUID=`uuidgen`

status_volume(){
	sinkName=`pacmd stat | awk -F': ' '/^Default sink name: / {print $2}'`

	while read -r line; do
		case $line in
			state:\ RUNNING)
				color='0F0' ;;
			muted:\ yes)
				color='F00' ;;
			active\ port:\ *headphone*)
				icon=$VOLUME_ICON_HEADPHONE ;;
			active\ port:*)
				icon=$VOLUME_ICON_SPEAKER ;;
			volume:*)
				read -r _ _ _ _ volume _ <<< "$line" ;;
		esac
	done < <(pacmd list-sinks | sed '/'"$sinkName"'/,/index:/!d')

	markup $icon $volume $color
}

watch_volume(){
	pactl subscribe 2>/dev/null | {
		while true; do
			{
				read -r event || break
				if ! grep "on card\|sink" <<< "$event"; then
					# avoid double events
					continue
				fi
			} &>/dev/null

			popup "`status_volume`" topright $VOLUME_UUID
		done
	}
}
