#!/bin/bash

cd `dirname "${BASH_SOURCE[0]}"`

source ./markup
source ./popup

source ./popup_clock
source ./popup_battery
source ./popup_network
source ./popup_vpn
source ./popup_volume
source ./popup_keyboard
source ./popup_updates

URGENT_COLOR=E44
ALL_UUID=`uuidgen`

# the updates popup tends to take time to load,
# let the user know we're about to show
popup "..." topleft $ALL_UUID

status=()
status+=("$(status_clock)")
status+=("$(status_battery)")
status+=("$(status_network)")
status+=("$(status_vpn)")
status+=("$(status_volume)")
status+=("$(status_keyboard)")
status+=("$(status_updates)")

# clear out empty indices
for i in "${!status[@]}"; do
	[[ -z "${status[$i]}" ]] && unset status[$i]
done

str="`printf "%s\n" "${status[@]}"`"
str="${str//[0-9A-F][0-9A-F][0-9A-F]/777}"
str="${str//RRR/$URGENT_COLOR}"

popup "$str" topleft $ALL_UUID
