#!/bin/bash

# colors
alias grep='grep --color=auto'
alias diff='diff --color=auto'

# shorthands
alias ls='exa --group-directories-first --time-style=long-iso -s Name'
alias ll='ls -l'
alias la='ll -a'
alias lt='ll -T'
alias rmd='rm -rf'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias -- -='cd -' # go to previous dir with "-"
alias cd.='cd $(readlink -f .)' # go to link source with ""
alias week='date +%V'
alias lm='stat -c "%a %n" *' # shows permissions for files in current directory
alias cpp='rsync -avPh'
alias mvp='rsync -avPh --remove-source-files'
alias cat='bat --theme=Toxin --style=numbers,changes'

# confirm before overwrite
alias cp='cp -i'
alias mv='mv -i'

# human-readable sizes
alias df='df -h'

# software-specific
alias py=python3
alias m=micro
alias xclip='xclip -selection clipboard'
alias vi=vim

if [[ -z "$SUDO_USER" ]]; then
	alias git="py ~/bin/hub"
fi
