#!/bin/sh

# create executable file
touchx(){
	touch "$1"
	chmod +x "$1"
}

# simple calculator
calc(){
	echo "$*" | bc -l;
}

# create a new directory and enter it
mk(){
	mkdir -p "$@" && cd "$@"
}

# all-in-one extract shorthand
extract(){
	if [ -f $1 ]; then
		case $1 in
			*.tar.bz2)	tar xjf $1	;;
			*.tar.gz)	tar xzf $1	;;
			*.bz2)		bunzip2 $1	;;
			*.rar)		unrar x $1	;;
			*.gz)		gunzip $1	;;
			*.tar)		tar xf $1	;;
			*.tbz2)		tar xjf $1	;;
			*.tgz)		tar xzf $1	;;
			*.zip)		unzip $1	;;
			*.Z)		uncompress $1	;;
			*.7z)		7z x $1		;;
			*)		echo "'$1' can't be extracted with extract" ;;
		esac
	else
		echo "'$1' is not a valid file"
	fi
}
