#!/bin/bash

colors=$(xrdb -query)

# workspaces
bspc monitor -d {1..9}

# gap and border
bspc config window_gap 10
bspc config border_width 1

# colors
bspc config normal_border_color "$(awk '/bspwm.inactive/ {print $2}' <<< "$colors")"
bspc config focused_border_color "$(awk '/bspwm.active/ {print $2}' <<< "$colors")"
bspc config presel_feedback_color "$(awk '/bspwm.preselect/ {print $2}' <<< "$colors")"

# application rules
bspc rule -a Firefox desktop='^1' private=on
bspc rule -a discord desktop='^5' private=on
# bspc rule -a Spotify desktop='^5' # https://github.com/baskerville/bspwm/issues/291
bspc rule -a Subl3 desktop='^2' private=on
bspc rule -a Enpass-Desktop desktop='^9'

bspc rule -a MEGAsync state=floating
bspc rule -a Galculator state=floating
bspc rule -a ranger_dialog state=floating

# settings
bspc config click_to_focus any
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config single_monocle true
