#!/bin/bash

# very basic file/directory "browser"
#
# requires:
# - rofi
# - feh (for viewing images)
# - gnome-mpv (for viewing videos)
# - zathura (for viewing pdfs)
# - ranger (for browsing directories)

# this is disgusting, wish the expressions supported regex properly (! -path '*.(cache|git)/*')
selection=$(rofi -dmenu -i -p 'Open: ' < <(find -L "$HOME" \
	! -path '*.cache/*' \
	! -path '*.git/*' \
	! -path '*.nuget/*' \
	! -path '*.mozilla/*' \
	! -path '*.local/*' \
	! -path '*.gem/*' \
	| sed 's@'"$HOME"'@~@g'))

selection="${selection/\~/$HOME}"
if [[ -f "$selection" ]]; then
	# it's a file, choose what to do based on mime type
	if [[ "$selection" = *.md ]]; then
		# special case for markdown
		$VISUAL -- "$selection"
	else
		mime=$(file -i "$selection" | awk -F': ' '{print $2}')
		if [[ "$mime" = text* ]]; then
			$VISUAL -- "$selection"
		elif [[ "$mime" = image* ]]; then
			feh -- "$selection"
		elif [[ "$mime" = video* ]]; then
			gnome-mpv -- "$selection"
		elif [[ "$mime" = application/pdf* ]]; then
			zathura -- "$selection"
		fi
		# TODO: handle archives
	fi
elif [[ -d "$selection" ]]; then
	# show directory with ranger
	# custom title so we can force floating mode in i3
	termite --class=ranger_dialog -e "ranger $selection"
fi
