#!/bin/sh

# outputs a colored icon and volume percentage
# - if muted, the icon is red
# - if headphone port is connected, shows a headphone icon
# - if no headphone is connected, shows a speaker icon
#
# requires:
# - pulseaudio (for pactl)
# - awk

ICON_SPEAKER=
ICON_HEADPHONE=

status(){
	local sink=$(pactl info | awk -F': ' '/^Default Sink/ {print $2}')
	local sinkId=$(pactl list short sinks | awk "/$sink/ {print \$1}")
	local offset=$(bc <<< "$sinkId + 1")

	local info=$(pactl list sinks)
	local state=$(echo "$info" | awk '/^[[:space:]]State/ {print $2}' | head -n $offset | tail -n 1)
	local volume=$(echo "$info" | awk '/^[[:space:]]Volume/ {print $5}' | head -n $offset | tail -n 1)
	local muted=$(echo "$info" | awk '/^[[:space:]]Mute:/ {print $2}' | head -n $offset | tail -n 1)
	local port=$(echo "$info" | awk '/^[[:space:]]Active Port:/ {print $3}' | head -n $offset | tail -n 1)

	local output='%{F#fff}'
	if [[ "$muted" = 'yes' ]]; then
		output='%{F#f00}'
	elif [[ "$state" = 'RUNNING' ]]; then
		output='%{F#0f0}'
	fi

	if [[ "$port" = *headphones ]]; then
		output+="$ICON_HEADPHONE"
	else
		output+="$ICON_SPEAKER"
	fi

	output+="%{F-} $volume"

	echo "$output"
}

status

# TODO: find a better solution to this mess
pactl subscribe 2>/dev/null | {
	while true; do
		{
			read -r event || break
			if ! echo "$event" | grep -e "on card" -e "on sink"; then
				# Avoid double events
				continue
			fi
		} &>/dev/null
		status
	done
}
